name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Configure git user
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'
      - name: Deploy
        run: |
          # Navigate to the public directory (submodule)
          cd public || exit 1

          # Configure git to use PAT
          REPO_NAME=$(gh repo view --json nameWithOwner -q ".nameWithOwner")
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO_NAME}.git"

          # Create a new branch name with timestamp
          RELEASE_BRANCH="release/$(date +%Y%m%d-%H%M%S)"
          
          # Make sure we're on the default branch first
          git checkout master
          git pull origin master
          
          # Create a new branch for this release
          git checkout -b $RELEASE_BRANCH
          
          # Add changes
          git add .
          
          # Commit changes
          git commit -m "Deploy: $(date)" || echo "No changes to commit"
          
          # Push the branch
          git push origin $RELEASE_BRANCH
          
          # Create a pull request using GitHub CLI
          gh pr create \
            --title "Deploy: $(date)" \
            --body "Automated deployment via GitHub Actions" \
            --base master \
            --head $RELEASE_BRANCH \
            --repo "$REPO_NAME"
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
