name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy
        run: |
          # Navigate to the public directory (submodule)
          cd public || exit 1
          
          # Configure git to use PAT
          git config --local url."https://x-access-token:${GH_TOKEN}@github.com/".insteadOf "https://github.com/"

          # Create a new branch name with timestamp
          RELEASE_BRANCH="release/$(date +%Y%m%d-%H%M%S)"
          
          # Make sure we're on the default branch first
          git checkout master
          git pull origin master
          
          # Create a new branch for this release
          git checkout -b $RELEASE_BRANCH
          
          # Add changes
          git add .
          
          # Commit changes
          git commit -m "Deploy: $(date)" || echo "No changes to commit"
          
          # Push the branch
          git push origin $RELEASE_BRANCH
          
          # Create a pull request using GitHub CLI
          REPO_NAME=$(git config --get remote.origin.url | sed 's/.*github.com[:/]\(.*\)\.git/\1/')
          gh pr create \
            --title "Deploy: $(date)" \
            --body "Automated deployment via GitHub Actions" \
            --base master \
            --head $RELEASE_BRANCH \
            --repo "$REPO_NAME"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
